- name: Setting up L3 interface on switch
  hosts: S1
  gather_facts: false
  

  tasks:
    - name: Set interface Vlan1 (SVI) IPv4 address
      ios_l3_interface:
       name: Vlan100
       ipv4: 192.168.0.5/24
    
      register: print_output

    -  debug: var=print_output.stdout_lines
