---
- name: Get MAC address table information
  hosts: S1
  gather_facts: false


  tasks:
    - name: show MAC address table
      ios_command: 
        commands: show mac address-table

      register: print_output

    -  debug: var=print_output.stdout_lines
